# Generated by GitHub Copilot on 2026-01-05

import django.db.models.deletion
from django.db import migrations, models


def backfill_image_type(apps, schema_editor):
    ImageType = apps.get_model("question", "ImageType")
    CroppedImage = apps.get_model("question", "CroppedImage")

    default_type, _ = ImageType.objects.get_or_create(name="General")
    CroppedImage.objects.filter(image_type__isnull=True).update(image_type=default_type)


class Migration(migrations.Migration):

    dependencies = [
        ("question", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(backfill_image_type, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="croppedimage",
            name="image_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="cropped_images",
                to="question.imagetype",
            ),
        ),
        migrations.AlterField(
            model_name="croppedimage",
            name="topic",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cropped_images",
                to="question.topic",
            ),
        ),
        migrations.AlterField(
            model_name="croppedimage",
            name="question_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cropped_images",
                to="question.questiontype",
            ),
        ),
        migrations.AlterField(
            model_name="croppedimage",
            name="marks",
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="croppedimage",
            name="priority",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="croppedimage",
            name="source",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cropped_images",
                to="question.sources",
            ),
        ),
    ]
