# Generated by GitHub Copilot on 2026-01-15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("question", "0003_croppedimage_align_required_optional"),
    ]

    operations = [
        migrations.CreateModel(
            name="CroppedImageExtra",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("image", models.ImageField(upload_to="cropped/")),
                ("image_type", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="cropped_image_extras", to="question.imagetype")),
                ("rect_pdf", models.JSONField(default=dict)),
                ("rect_screen", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("parent", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="extra_images", to="question.croppedimage")),
            ],
        ),
    ]
