# Generated by GitHub Copilot on 2026-01-15

from django.db import migrations, models


def backfill_sort_order(apps, schema_editor):
    CroppedImageExtra = apps.get_model("question", "CroppedImageExtra")

    # For existing rows, set sort_order per parent based on creation/id order.
    parent_ids = (
        CroppedImageExtra.objects.order_by()
        .values_list("parent_id", flat=True)
        .distinct()
    )

    for parent_id in parent_ids:
        extras = list(
            CroppedImageExtra.objects.filter(parent_id=parent_id).order_by("created_at", "id")
        )
        # Primary is implicitly 1. Extras start at 2.
        for i, extra in enumerate(extras, start=2):
            if not extra.sort_order:
                CroppedImageExtra.objects.filter(pk=extra.pk).update(sort_order=i)


class Migration(migrations.Migration):

    dependencies = [
        ("question", "0004_croppedimageextra"),
    ]

    operations = [
        migrations.AddField(
            model_name="croppedimageextra",
            name="sort_order",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.RunPython(backfill_sort_order, migrations.RunPython.noop),
    ]
