from django.urls import path
from .views import (
    ChapterBulk,
    ChapterDetail,
    ChapterList,
    ClassBulk,
    ClassDetail,
    ClassList,
    ConceptBulk,
    ConceptDetail,
    ConceptList,
    CroppedImageDetail,
    CroppedImageList,
    ImageTypeList,
    QuestionTypeList,
    SourcesList,
    SubjectBulk,
    SubjectDetail,
    SubjectList,
    TopicBulk,
    TopicDetail,
    TopicList,
    UploadCrop,
    UploadCropBulk,
    UsageTypeList,
)

urlpatterns = [
    path("api/upload-crop/", UploadCrop.as_view()),
    path("api/upload-crop-bulk/", UploadCropBulk.as_view()),
    path("api/classes/", ClassList.as_view()),
    path("api/classes/bulk/", ClassBulk.as_view()),
    path("api/classes/<int:pk>/", ClassDetail.as_view()),
    path("api/subjects/", SubjectList.as_view()),
    path("api/subjects/bulk/", SubjectBulk.as_view()),
    path("api/subjects/<int:pk>/", SubjectDetail.as_view()),
    path("api/chapters/", ChapterList.as_view()),
    path("api/chapters/bulk/", ChapterBulk.as_view()),
    path("api/chapters/<int:pk>/", ChapterDetail.as_view()),
    path("api/concepts/", ConceptList.as_view()),
    path("api/concepts/bulk/", ConceptBulk.as_view()),
    path("api/concepts/<int:pk>/", ConceptDetail.as_view()),
    path("api/topics/", TopicList.as_view()),
    path("api/topics/bulk/", TopicBulk.as_view()),
    path("api/topics/<int:pk>/", TopicDetail.as_view()),
    path("api/image-types/", ImageTypeList.as_view()),
    path("api/question-types/", QuestionTypeList.as_view()),
    path("api/usage-types/", UsageTypeList.as_view()),
    path("api/sources/", SourcesList.as_view()),
    path("api/cropped-images/", CroppedImageList.as_view()),
    path("api/cropped-images/<int:pk>/", CroppedImageDetail.as_view()),
]
